### ISSUE TITLE
bftest and the stepping stone sampler

### ISSUE THREAD

**Issue by Ax3man** [rgriff23/btw#3]
The manual seem to suggest the Bayes Factor must be computed using the marginal likelihoods instead of the maximum likelihoods, the former of which can be estimated using the stepping stone sampler.

Shouldn't `bftest` therefore use the `Stones` output instead of the `Log$results$Lh` as it does now? Did I misunderstand?

**Comment by rgriff23** [comment]
You are correct, thank you for catching this! I have fixed the bftest function.
